### ISSUE TITLE
Lag 

### ISSUE THREAD

**Issue by kaneishere** [kenrick95/plan#15]
Am a double degree student using your website. Upon entering the courses, the website would load for a very long period of time (1 to 2 minutes) without showing any result. I took out all my business modules and tried again and it loaded instantly.

**Comment by kenrick95** [comment]
Can you share what are the course codes that you enter? Thanks

**Comment by kaneishere** [comment]
Hi, the codes I entered were AD1011, AB0601, AB1601, CZ1005, CZ1006, CZ1007, CZ1015 and LF9001

**Comment by kenrick95** [comment]
Okay, when I tried out and enter a few of your courses, it seemed that it has generated so many possibilities for you to choose, simply because those courses have many index that does not have schedule conflict with one another. 

For example, entering CZ1015, CZ1007, LF9001, and AD1101 generates 5304 possibilities, and when you enter more and more courses, it will get slower and slower (simply because it can't iterate through all the possibilities).

When you see the loading bar spinning for more than 30s, it's a good sign that server has given up and returns an error (but we didn't handle this case and show it to you; I guess this is a room for improvement)

My advise to you is that you might not need this tool, given that these courses already yield so many possibilities even when you query them partially. This tools is more for people that have given up on STARS Planner finding the combination of indices that fits all the courses that they wanted to take.

Regards,
Kenrick
