### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by aqualific** [kenrick95/plan#23]
"We're sorry. Server has returned an error. Please try again with different queries." message was displayed after correctly selecting the courses planned out for sem 2. May I know what's the issue? 
I tried selecting both my school and "others" in the drop-down list, and made sure that none of the time slots were checked under "free time".

**Comment by kenrick95** [comment]
That is because the courses that you input yields _so_ many possibilities that the server cannot list them all out in time. You can try inputting less courses. Sorry about that, this project is no longer in development and here only for maintenance (like updating data and fixing minor bugs). Thanks for understanding
